window.RACE_DATA = {
  "location": "London",
  "currency": "GBP",
  "source": {
    "label": "Welcome to the Jungle salaries",
    "url": "https://app.welcometothejungle.com/salaries"
  },
  "narrative": {
    "title": "The London salary rat race",
    "dek": "Nine roles start in a pack, then stretch into a breakaway by mid-career."
  },
  "roles": [
    {
      "role": "Generalist Marketing",
      "laneIndex": 0,
      "color": "#ff6a3d",
      "series": [
        {
          "role_id": "18",
          "role": "Generalist Marketing",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 818,
          "years_experience": 0,
          "first_decile": 25000,
          "first_quartile": 26500,
          "median": 30000,
          "last_quartile": 36000,
          "last_decile": 38500
        },
        {
          "role_id": "18",
          "role": "Generalist Marketing",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 818,
          "years_experience": 1,
          "first_decile": 26500,
          "first_quartile": 27500,
          "median": 32000,
          "last_quartile": 39500,
          "last_decile": 45000
        },
        {
          "role_id": "18",
          "role": "Generalist Marketing",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 818,
          "years_experience": 2,
          "first_decile": 27500,
          "first_quartile": 29500,
          "median": 34000,
          "last_quartile": 41000,
          "last_decile": 48000
        },
        {
          "role_id": "18",
          "role": "Generalist Marketing",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 818,
          "years_experience": 3,
          "first_decile": 30000,
          "first_quartile": 36000,
          "median": 45000,
          "last_quartile": 52500,
          "last_decile": 60000
        },
        {
          "role_id": "18",
          "role": "Generalist Marketing",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 818,
          "years_experience": 4,
          "first_decile": 31000,
          "first_quartile": 37000,
          "median": 47000,
          "last_quartile": 55000,
          "last_decile": 64500
        },
        {
          "role_id": "18",
          "role": "Generalist Marketing",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 818,
          "years_experience": 5,
          "first_decile": 38500,
          "first_quartile": 50000,
          "median": 62000,
          "last_quartile": 80000,
          "last_decile": 93000
        },
        {
          "role_id": "18",
          "role": "Generalist Marketing",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 818,
          "years_experience": 6,
          "first_decile": 39500,
          "first_quartile": 51000,
          "median": 66000,
          "last_quartile": 84000,
          "last_decile": 100000
        },
        {
          "role_id": "18",
          "role": "Generalist Marketing",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 818,
          "years_experience": 7,
          "first_decile": 40500,
          "first_quartile": 53000,
          "median": 68000,
          "last_quartile": 88000,
          "last_decile": 103000
        },
        {
          "role_id": "18",
          "role": "Generalist Marketing",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 818,
          "years_experience": 8,
          "first_decile": 42000,
          "first_quartile": 55000,
          "median": 70000,
          "last_quartile": 92000,
          "last_decile": 108000
        },
        {
          "role_id": "18",
          "role": "Generalist Marketing",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 818,
          "years_experience": 9,
          "first_decile": 58500,
          "first_quartile": 77000,
          "median": 93500,
          "last_quartile": 106500,
          "last_decile": 138000
        }
      ],
      "y0": 30000,
      "y3": 45000,
      "y5": 62000,
      "y9": 93500,
      "growth0to3": 15000,
      "growth0to5": 32000,
      "growth0to9": 63500
    },
    {
      "role": "Finance Operations",
      "laneIndex": 1,
      "color": "#ffffff",
      "series": [
        {
          "role_id": "31",
          "role": "Finance Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 355,
          "years_experience": 0,
          "first_decile": 24000,
          "first_quartile": 25000,
          "median": 28000,
          "last_quartile": 30000,
          "last_decile": 32000
        },
        {
          "role_id": "31",
          "role": "Finance Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 355,
          "years_experience": 1,
          "first_decile": 27500,
          "first_quartile": 30000,
          "median": 32500,
          "last_quartile": 36000,
          "last_decile": 40000
        },
        {
          "role_id": "31",
          "role": "Finance Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 355,
          "years_experience": 2,
          "first_decile": 30000,
          "first_quartile": 33000,
          "median": 37000,
          "last_quartile": 40000,
          "last_decile": 41500
        },
        {
          "role_id": "31",
          "role": "Finance Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 355,
          "years_experience": 3,
          "first_decile": 35000,
          "first_quartile": 41000,
          "median": 50000,
          "last_quartile": 69000,
          "last_decile": 81500
        },
        {
          "role_id": "31",
          "role": "Finance Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 355,
          "years_experience": 4,
          "first_decile": 36000,
          "first_quartile": 45000,
          "median": 52500,
          "last_quartile": 74500,
          "last_decile": 84000
        },
        {
          "role_id": "31",
          "role": "Finance Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 355,
          "years_experience": 5,
          "first_decile": 50500,
          "first_quartile": 65500,
          "median": 79000,
          "last_quartile": 87500,
          "last_decile": 102500
        },
        {
          "role_id": "31",
          "role": "Finance Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 355,
          "years_experience": 6,
          "first_decile": 51500,
          "first_quartile": 67500,
          "median": 81500,
          "last_quartile": 92500,
          "last_decile": 109000
        },
        {
          "role_id": "31",
          "role": "Finance Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 355,
          "years_experience": 7,
          "first_decile": 52500,
          "first_quartile": 70000,
          "median": 84000,
          "last_quartile": 97500,
          "last_decile": 113000
        },
        {
          "role_id": "31",
          "role": "Finance Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 355,
          "years_experience": 8,
          "first_decile": 53500,
          "first_quartile": 72500,
          "median": 89000,
          "last_quartile": 103000,
          "last_decile": 118000
        },
        {
          "role_id": "31",
          "role": "Finance Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 355,
          "years_experience": 9,
          "first_decile": 63000,
          "first_quartile": 78000,
          "median": 94500,
          "last_quartile": 117500,
          "last_decile": 128000
        }
      ],
      "y0": 28000,
      "y3": 50000,
      "y5": 79000,
      "y9": 94500,
      "growth0to3": 22000,
      "growth0to5": 51000,
      "growth0to9": 66500
    },
    {
      "role": "Sales Operations",
      "laneIndex": 2,
      "color": "#f3d338",
      "series": [
        {
          "role_id": "122",
          "role": "Sales Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 578,
          "years_experience": 0,
          "first_decile": 29500,
          "first_quartile": 30000,
          "median": 30000,
          "last_quartile": 32000,
          "last_decile": 38000
        },
        {
          "role_id": "122",
          "role": "Sales Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 578,
          "years_experience": 1,
          "first_decile": 30000,
          "first_quartile": 31500,
          "median": 45000,
          "last_quartile": 57000,
          "last_decile": 60000
        },
        {
          "role_id": "122",
          "role": "Sales Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 578,
          "years_experience": 2,
          "first_decile": 30000,
          "first_quartile": 33000,
          "median": 47500,
          "last_quartile": 62000,
          "last_decile": 65500
        },
        {
          "role_id": "122",
          "role": "Sales Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 578,
          "years_experience": 3,
          "first_decile": 34500,
          "first_quartile": 48000,
          "median": 56000,
          "last_quartile": 68000,
          "last_decile": 75000
        },
        {
          "role_id": "122",
          "role": "Sales Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 578,
          "years_experience": 4,
          "first_decile": 36500,
          "first_quartile": 50000,
          "median": 60000,
          "last_quartile": 74500,
          "last_decile": 77000
        },
        {
          "role_id": "122",
          "role": "Sales Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 578,
          "years_experience": 5,
          "first_decile": 50000,
          "first_quartile": 60000,
          "median": 74000,
          "last_quartile": 83500,
          "last_decile": 120000
        },
        {
          "role_id": "122",
          "role": "Sales Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 578,
          "years_experience": 6,
          "first_decile": 51500,
          "first_quartile": 62500,
          "median": 78000,
          "last_quartile": 90500,
          "last_decile": 125000
        },
        {
          "role_id": "122",
          "role": "Sales Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 578,
          "years_experience": 7,
          "first_decile": 54000,
          "first_quartile": 66000,
          "median": 82000,
          "last_quartile": 97000,
          "last_decile": 133000
        },
        {
          "role_id": "122",
          "role": "Sales Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 578,
          "years_experience": 8,
          "first_decile": 59000,
          "first_quartile": 70000,
          "median": 84500,
          "last_quartile": 104000,
          "last_decile": 143500
        },
        {
          "role_id": "122",
          "role": "Sales Operations",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 578,
          "years_experience": 9,
          "first_decile": 77000,
          "first_quartile": 87000,
          "median": 112000,
          "last_quartile": 133000,
          "last_decile": 168500
        }
      ],
      "y0": 30000,
      "y3": 56000,
      "y5": 74000,
      "y9": 112000,
      "growth0to3": 26000,
      "growth0to5": 44000,
      "growth0to9": 82000
    },
    {
      "role": "Risk & Compliance",
      "laneIndex": 3,
      "color": "#0b8b63",
      "series": [
        {
          "role_id": "29",
          "role": "Risk & Compliance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1461,
          "years_experience": 0,
          "first_decile": 27000,
          "first_quartile": 28000,
          "median": 31500,
          "last_quartile": 34500,
          "last_decile": 35000
        },
        {
          "role_id": "29",
          "role": "Risk & Compliance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1461,
          "years_experience": 1,
          "first_decile": 29000,
          "first_quartile": 31500,
          "median": 35000,
          "last_quartile": 43000,
          "last_decile": 53500
        },
        {
          "role_id": "29",
          "role": "Risk & Compliance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1461,
          "years_experience": 2,
          "first_decile": 30500,
          "first_quartile": 33000,
          "median": 38000,
          "last_quartile": 47500,
          "last_decile": 56500
        },
        {
          "role_id": "29",
          "role": "Risk & Compliance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1461,
          "years_experience": 3,
          "first_decile": 36500,
          "first_quartile": 45000,
          "median": 57000,
          "last_quartile": 70000,
          "last_decile": 80000
        },
        {
          "role_id": "29",
          "role": "Risk & Compliance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1461,
          "years_experience": 4,
          "first_decile": 39500,
          "first_quartile": 49000,
          "median": 59500,
          "last_quartile": 73500,
          "last_decile": 84000
        },
        {
          "role_id": "29",
          "role": "Risk & Compliance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1461,
          "years_experience": 5,
          "first_decile": 54000,
          "first_quartile": 62000,
          "median": 77000,
          "last_quartile": 89000,
          "last_decile": 112000
        },
        {
          "role_id": "29",
          "role": "Risk & Compliance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1461,
          "years_experience": 6,
          "first_decile": 56000,
          "first_quartile": 66000,
          "median": 81000,
          "last_quartile": 94000,
          "last_decile": 121000
        },
        {
          "role_id": "29",
          "role": "Risk & Compliance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1461,
          "years_experience": 7,
          "first_decile": 58000,
          "first_quartile": 69500,
          "median": 86000,
          "last_quartile": 99000,
          "last_decile": 127000
        },
        {
          "role_id": "29",
          "role": "Risk & Compliance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1461,
          "years_experience": 8,
          "first_decile": 60000,
          "first_quartile": 73000,
          "median": 90000,
          "last_quartile": 104500,
          "last_decile": 133000
        },
        {
          "role_id": "29",
          "role": "Risk & Compliance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1461,
          "years_experience": 9,
          "first_decile": 75000,
          "first_quartile": 84000,
          "median": 110000,
          "last_quartile": 124000,
          "last_decile": 153000
        }
      ],
      "y0": 31500,
      "y3": 57000,
      "y5": 77000,
      "y9": 110000,
      "growth0to3": 25500,
      "growth0to5": 45500,
      "growth0to9": 78500
    },
    {
      "role": "Corporate Finance",
      "laneIndex": 4,
      "color": "#d81f33",
      "series": [
        {
          "role_id": "58",
          "role": "Corporate Finance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 244,
          "years_experience": 0,
          "first_decile": 27000,
          "first_quartile": 27000,
          "median": 28000,
          "last_quartile": 29500,
          "last_decile": 32500
        },
        {
          "role_id": "58",
          "role": "Corporate Finance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 244,
          "years_experience": 1,
          "first_decile": 28000,
          "first_quartile": 30000,
          "median": 37000,
          "last_quartile": 54000,
          "last_decile": 78500
        },
        {
          "role_id": "58",
          "role": "Corporate Finance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 244,
          "years_experience": 2,
          "first_decile": 37000,
          "first_quartile": 39500,
          "median": 47500,
          "last_quartile": 72500,
          "last_decile": 86500
        },
        {
          "role_id": "58",
          "role": "Corporate Finance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 244,
          "years_experience": 3,
          "first_decile": 40000,
          "first_quartile": 53000,
          "median": 68000,
          "last_quartile": 75000,
          "last_decile": 94000
        },
        {
          "role_id": "58",
          "role": "Corporate Finance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 244,
          "years_experience": 4,
          "first_decile": 45500,
          "first_quartile": 54000,
          "median": 70500,
          "last_quartile": 76500,
          "last_decile": 97000
        },
        {
          "role_id": "58",
          "role": "Corporate Finance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 244,
          "years_experience": 5,
          "first_decile": 58500,
          "first_quartile": 70000,
          "median": 82000,
          "last_quartile": 100000,
          "last_decile": 114500
        },
        {
          "role_id": "58",
          "role": "Corporate Finance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 244,
          "years_experience": 6,
          "first_decile": 60000,
          "first_quartile": 72000,
          "median": 84000,
          "last_quartile": 110000,
          "last_decile": 121500
        },
        {
          "role_id": "58",
          "role": "Corporate Finance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 244,
          "years_experience": 7,
          "first_decile": 63000,
          "first_quartile": 75500,
          "median": 88000,
          "last_quartile": 115000,
          "last_decile": 128000
        },
        {
          "role_id": "58",
          "role": "Corporate Finance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 244,
          "years_experience": 8,
          "first_decile": 67000,
          "first_quartile": 78500,
          "median": 92500,
          "last_quartile": 117000,
          "last_decile": 136000
        },
        {
          "role_id": "58",
          "role": "Corporate Finance",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 244,
          "years_experience": 9,
          "first_decile": 78000,
          "first_quartile": 86500,
          "median": 115000,
          "last_quartile": 129500,
          "last_decile": 163500
        }
      ],
      "y0": 28000,
      "y3": 68000,
      "y5": 82000,
      "y9": 115000,
      "growth0to3": 40000,
      "growth0to5": 54000,
      "growth0to9": 87000
    },
    {
      "role": "Product Management",
      "laneIndex": 5,
      "color": "#0f49c7",
      "series": [
        {
          "role_id": "43",
          "role": "Product Management",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2084,
          "years_experience": 0,
          "first_decile": 28000,
          "first_quartile": 28000,
          "median": 29500,
          "last_quartile": 31000,
          "last_decile": 31500
        },
        {
          "role_id": "43",
          "role": "Product Management",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2084,
          "years_experience": 1,
          "first_decile": 30500,
          "first_quartile": 43500,
          "median": 50000,
          "last_quartile": 55000,
          "last_decile": 70000
        },
        {
          "role_id": "43",
          "role": "Product Management",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2084,
          "years_experience": 2,
          "first_decile": 35000,
          "first_quartile": 50000,
          "median": 54000,
          "last_quartile": 60500,
          "last_decile": 75000
        },
        {
          "role_id": "43",
          "role": "Product Management",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2084,
          "years_experience": 3,
          "first_decile": 50000,
          "first_quartile": 58000,
          "median": 65000,
          "last_quartile": 75000,
          "last_decile": 90000
        },
        {
          "role_id": "43",
          "role": "Product Management",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2084,
          "years_experience": 4,
          "first_decile": 54000,
          "first_quartile": 63000,
          "median": 69000,
          "last_quartile": 81000,
          "last_decile": 95500
        },
        {
          "role_id": "43",
          "role": "Product Management",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2084,
          "years_experience": 5,
          "first_decile": 65000,
          "first_quartile": 75000,
          "median": 86000,
          "last_quartile": 100500,
          "last_decile": 120000
        },
        {
          "role_id": "43",
          "role": "Product Management",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2084,
          "years_experience": 6,
          "first_decile": 68000,
          "first_quartile": 77000,
          "median": 92000,
          "last_quartile": 108500,
          "last_decile": 125000
        },
        {
          "role_id": "43",
          "role": "Product Management",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2084,
          "years_experience": 7,
          "first_decile": 72000,
          "first_quartile": 81000,
          "median": 97000,
          "last_quartile": 114500,
          "last_decile": 130000
        },
        {
          "role_id": "43",
          "role": "Product Management",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2084,
          "years_experience": 8,
          "first_decile": 75000,
          "first_quartile": 85000,
          "median": 104000,
          "last_quartile": 120000,
          "last_decile": 135000
        },
        {
          "role_id": "43",
          "role": "Product Management",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2084,
          "years_experience": 9,
          "first_decile": 84000,
          "first_quartile": 96000,
          "median": 112000,
          "last_quartile": 132500,
          "last_decile": 146000
        }
      ],
      "y0": 29500,
      "y3": 65000,
      "y5": 86000,
      "y9": 112000,
      "growth0to3": 35500,
      "growth0to5": 56500,
      "growth0to9": 82500
    },
    {
      "role": "Legal",
      "laneIndex": 6,
      "color": "#ff9a3c",
      "series": [
        {
          "role_id": "27",
          "role": "Legal",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 501,
          "years_experience": 0,
          "first_decile": 30500,
          "first_quartile": 31000,
          "median": 35000,
          "last_quartile": 37000,
          "last_decile": 39000
        },
        {
          "role_id": "27",
          "role": "Legal",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 501,
          "years_experience": 1,
          "first_decile": 34000,
          "first_quartile": 37000,
          "median": 38000,
          "last_quartile": 52500,
          "last_decile": 60000
        },
        {
          "role_id": "27",
          "role": "Legal",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 501,
          "years_experience": 2,
          "first_decile": 34500,
          "first_quartile": 38500,
          "median": 40000,
          "last_quartile": 56500,
          "last_decile": 78000
        },
        {
          "role_id": "27",
          "role": "Legal",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 501,
          "years_experience": 3,
          "first_decile": 41000,
          "first_quartile": 47500,
          "median": 60000,
          "last_quartile": 70000,
          "last_decile": 87000
        },
        {
          "role_id": "27",
          "role": "Legal",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 501,
          "years_experience": 4,
          "first_decile": 43000,
          "first_quartile": 52000,
          "median": 62000,
          "last_quartile": 75000,
          "last_decile": 94000
        },
        {
          "role_id": "27",
          "role": "Legal",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 501,
          "years_experience": 5,
          "first_decile": 55500,
          "first_quartile": 65000,
          "median": 85000,
          "last_quartile": 100000,
          "last_decile": 140000
        },
        {
          "role_id": "27",
          "role": "Legal",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 501,
          "years_experience": 6,
          "first_decile": 57500,
          "first_quartile": 69000,
          "median": 88000,
          "last_quartile": 108000,
          "last_decile": 148000
        },
        {
          "role_id": "27",
          "role": "Legal",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 501,
          "years_experience": 7,
          "first_decile": 62500,
          "first_quartile": 72000,
          "median": 91000,
          "last_quartile": 112000,
          "last_decile": 156000
        },
        {
          "role_id": "27",
          "role": "Legal",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 501,
          "years_experience": 8,
          "first_decile": 65000,
          "first_quartile": 75000,
          "median": 94500,
          "last_quartile": 116000,
          "last_decile": 163500
        },
        {
          "role_id": "27",
          "role": "Legal",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 501,
          "years_experience": 9,
          "first_decile": 76000,
          "first_quartile": 90000,
          "median": 114000,
          "last_quartile": 130000,
          "last_decile": 170500
        }
      ],
      "y0": 35000,
      "y3": 60000,
      "y5": 85000,
      "y9": 114000,
      "growth0to3": 25000,
      "growth0to5": 50000,
      "growth0to9": 79000
    },
    {
      "role": "Data Analysis & BI",
      "laneIndex": 7,
      "color": "#2cc7ff",
      "series": [
        {
          "role_id": "5",
          "role": "Data Analysis & BI",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1566,
          "years_experience": 0,
          "first_decile": 28000,
          "first_quartile": 29500,
          "median": 33000,
          "last_quartile": 36000,
          "last_decile": 41000
        },
        {
          "role_id": "5",
          "role": "Data Analysis & BI",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1566,
          "years_experience": 1,
          "first_decile": 32000,
          "first_quartile": 37000,
          "median": 40000,
          "last_quartile": 45000,
          "last_decile": 55500
        },
        {
          "role_id": "5",
          "role": "Data Analysis & BI",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1566,
          "years_experience": 2,
          "first_decile": 35000,
          "first_quartile": 41500,
          "median": 45000,
          "last_quartile": 50000,
          "last_decile": 59000
        },
        {
          "role_id": "5",
          "role": "Data Analysis & BI",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1566,
          "years_experience": 3,
          "first_decile": 40000,
          "first_quartile": 46500,
          "median": 54500,
          "last_quartile": 62500,
          "last_decile": 75000
        },
        {
          "role_id": "5",
          "role": "Data Analysis & BI",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1566,
          "years_experience": 4,
          "first_decile": 43000,
          "first_quartile": 50000,
          "median": 59500,
          "last_quartile": 69500,
          "last_decile": 80000
        },
        {
          "role_id": "5",
          "role": "Data Analysis & BI",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1566,
          "years_experience": 5,
          "first_decile": 50000,
          "first_quartile": 60000,
          "median": 68000,
          "last_quartile": 80000,
          "last_decile": 100000
        },
        {
          "role_id": "5",
          "role": "Data Analysis & BI",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1566,
          "years_experience": 6,
          "first_decile": 52000,
          "first_quartile": 63000,
          "median": 72000,
          "last_quartile": 86000,
          "last_decile": 105000
        },
        {
          "role_id": "5",
          "role": "Data Analysis & BI",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1566,
          "years_experience": 7,
          "first_decile": 53500,
          "first_quartile": 66000,
          "median": 76000,
          "last_quartile": 90500,
          "last_decile": 110000
        },
        {
          "role_id": "5",
          "role": "Data Analysis & BI",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1566,
          "years_experience": 8,
          "first_decile": 55500,
          "first_quartile": 69000,
          "median": 80000,
          "last_quartile": 95000,
          "last_decile": 115000
        },
        {
          "role_id": "5",
          "role": "Data Analysis & BI",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 1566,
          "years_experience": 9,
          "first_decile": 68000,
          "first_quartile": 74000,
          "median": 95000,
          "last_quartile": 108500,
          "last_decile": 120000
        }
      ],
      "y0": 33000,
      "y3": 54500,
      "y5": 68000,
      "y9": 95000,
      "growth0to3": 21500,
      "growth0to5": 35000,
      "growth0to9": 62000
    },
    {
      "role": "Backend Engineer",
      "laneIndex": 8,
      "color": "#08111f",
      "series": [
        {
          "role_id": "7",
          "role": "Backend Engineer",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2122,
          "years_experience": 0,
          "first_decile": 38000,
          "first_quartile": 39000,
          "median": 44000,
          "last_quartile": 46500,
          "last_decile": 47000
        },
        {
          "role_id": "7",
          "role": "Backend Engineer",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2122,
          "years_experience": 1,
          "first_decile": 45000,
          "first_quartile": 46000,
          "median": 55000,
          "last_quartile": 65000,
          "last_decile": 75500
        },
        {
          "role_id": "7",
          "role": "Backend Engineer",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2122,
          "years_experience": 2,
          "first_decile": 48000,
          "first_quartile": 51000,
          "median": 61500,
          "last_quartile": 68500,
          "last_decile": 82000
        },
        {
          "role_id": "7",
          "role": "Backend Engineer",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2122,
          "years_experience": 3,
          "first_decile": 50000,
          "first_quartile": 58500,
          "median": 66000,
          "last_quartile": 75000,
          "last_decile": 90000
        },
        {
          "role_id": "7",
          "role": "Backend Engineer",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2122,
          "years_experience": 4,
          "first_decile": 52000,
          "first_quartile": 61500,
          "median": 71500,
          "last_quartile": 84000,
          "last_decile": 94500
        },
        {
          "role_id": "7",
          "role": "Backend Engineer",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2122,
          "years_experience": 5,
          "first_decile": 62000,
          "first_quartile": 73500,
          "median": 85000,
          "last_quartile": 98500,
          "last_decile": 108000
        },
        {
          "role_id": "7",
          "role": "Backend Engineer",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2122,
          "years_experience": 6,
          "first_decile": 66500,
          "first_quartile": 77000,
          "median": 89000,
          "last_quartile": 103000,
          "last_decile": 116500
        },
        {
          "role_id": "7",
          "role": "Backend Engineer",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2122,
          "years_experience": 7,
          "first_decile": 69500,
          "first_quartile": 81000,
          "median": 93000,
          "last_quartile": 108000,
          "last_decile": 124500
        },
        {
          "role_id": "7",
          "role": "Backend Engineer",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2122,
          "years_experience": 8,
          "first_decile": 72500,
          "first_quartile": 85000,
          "median": 97000,
          "last_quartile": 115000,
          "last_decile": 131500
        },
        {
          "role_id": "7",
          "role": "Backend Engineer",
          "location": "LONDON",
          "currency": "GBP",
          "num_raw_datapoints": 2122,
          "years_experience": 9,
          "first_decile": 85000,
          "first_quartile": 98500,
          "median": 106000,
          "last_quartile": 125000,
          "last_decile": 143000
        }
      ],
      "y0": 44000,
      "y3": 66000,
      "y5": 85000,
      "y9": 106000,
      "growth0to3": 22000,
      "growth0to5": 41000,
      "growth0to9": 62000
    }
  ],
  "steps": [
    {
      "id": "start",
      "year": 0,
      "title": "A tight pack at the gun",
      "body": "Most of these roles leave the blocks in a narrow salary band. The race is crowded, and the early leaderboard is not yet destiny.",
      "callouts": [
        "Backend Engineer",
        "Legal",
        "Generalist Marketing"
      ]
    },
    {
      "id": "first-bend",
      "year": 3,
      "title": "The first bend changes the order",
      "body": "By year three, Product Management and Corporate Finance begin to separate. Several others are still close enough to draft behind them.",
      "callouts": [
        "Product Management",
        "Corporate Finance",
        "Data Analysis & BI"
      ]
    },
    {
      "id": "breakaway",
      "year": 5,
      "title": "The breakaway happens at mid-career",
      "body": "Year five is where the underdog breakaway becomes legible. Product Management, Corporate Finance, and Legal all gain serious ground, while Generalist Marketing and Sales Operations stay in contention.",
      "callouts": [
        "Product Management",
        "Corporate Finance",
        "Legal",
        "Sales Operations"
      ]
    },
    {
      "id": "finish",
      "year": 9,
      "title": "The finish line is about slope, not just starting position",
      "body": "At the finish, some roles that did not begin at the front have surged into the leading group. Hover any runner to inspect the exact split and gain.",
      "callouts": [
        "Product Management",
        "Corporate Finance",
        "Risk & Compliance",
        "Generalist Marketing"
      ]
    }
  ],
  "maxSalary": 115000
};
